design:

web:
  slug: web
  title: Web Design & Development
apps:
  slug: apps
  title: Mobile App Design & Development
graphics:
  slug: graphics
  title: Graphic Design
social:
  slug: social
  title: Social Media Setups
